from prolothar_queue_mining.model.exit.exit import Exit
from prolothar_queue_mining.model.exit.list_collector import ListCollectorExit
from prolothar_queue_mining.model.exit.do_nothing import DoNothingExit