from prolothar_queue_mining.model.observer.sojourn_time.sojourn_time_observer import SojournTimeObserver
from prolothar_queue_mining.model.observer.sojourn_time.null_sojourn_time_observer import NullSojournTimeObserver
from prolothar_queue_mining.model.observer.sojourn_time.sojourn_time_recording_observer import SojournTimeRecordingObserver