from typing import Callable
from prolothar_queue_mining.model.event import Event

class EventQueue:
    def enqueue(self, event: Event): ...
    def pop(self) -> Event: ...
    def is_non_empty(self) -> bool: ...

class Environment:
    def has_open_events(self) -> bool: ...
    def run_timesteps(self, timesteps: int): ...
    def run_until(self, condition: Callable[[], bool]): ...
    def run_until_event_queue_is_empty(self): ...
    def schedule_event(self, event: Event): ...
    def get_current_time(self) -> int: ...