from prolothar_queue_mining.model.environment import Environment
from prolothar_queue_mining.model.server import Server
from prolothar_queue_mining.model.job import Job
from prolothar_queue_mining.model.waiting_area import WaitingArea

class Queue:

    def get_waiting_area(self) -> WaitingArea: ...
    def handle_job_arrival(self, environment: Environment, arrival_time: int, job: Job): ...
    def try_to_serve_next_job(self, environment: Environment): ...
    def handle_batch_exit(self, environment: Environment, server: Server, exit_time: int, batch: list[Job]): ...
    def handle_job_exit(self, environment: Environment, server: Server, exit_time: int, job: Job): ...
    def schedule_next_arrival(self, environment: Environment): ...
    def copy(self) -> 'Queue': ...
