from prolothar_queue_mining.inference.queue.waiting_area.waiting_area_estimator import WaitingAreaEstimator
from prolothar_queue_mining.inference.queue.waiting_area.priority_class_waiting_area_estimator import PriorityClassWaitingAreaEstimator
from prolothar_queue_mining.inference.queue.waiting_area.pairwise_logistic_regression_cv_estimator import PairwiseLogisticRegressionCvEstimator
from prolothar_queue_mining.inference.queue.waiting_area.pairwise_random_forest_cv_estimator import PairwiseRandomForestCvEstimator
from prolothar_queue_mining.inference.queue.waiting_area.linear_regression_estimator import LinearRegressionEstimator
from prolothar_queue_mining.inference.queue.waiting_area.naive_lifo_or_fifo_estimator import NaiveLifoOrFifoWaitingAreaEstimator
from prolothar_queue_mining.inference.queue.waiting_area.flifo_estimator import FlifoWaitingAreaEstimator