from prolothar_queue_mining.model.observer.waiting_time.waiting_time_observer import WaitingTimeObserver
from prolothar_queue_mining.model.observer.waiting_time.null_waiting_time_observer import NullWaitingTimeObserver
from prolothar_queue_mining.model.observer.waiting_time.waiting_time_recording_observer import WaitingTimeRecordingObserver
from prolothar_queue_mining.model.observer.waiting_time.serve_order_recorder import ServeOrderRecorder