from prolothar_queue_mining.model.population.population import Population
from prolothar_queue_mining.model.population.list_population import ListPopulation
from prolothar_queue_mining.model.population.infinite_population import InfinitePopulation
from prolothar_queue_mining.model.population.list_with_replacement_population import ListWithReplacementPopulation